apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rpe-pdf-service"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_j_to_z/rpe-pdf-service
    github.com/project-slug: hmcts/rpe-pdf-service
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=platops-help
      title: "#platops-help on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dts_platform_operations
